### PR TITLE
reading through

### PR DESCRIPTION
**Pull request by ltalirz**

### CODE REVIEW

**Comment by kjappelbaum** [comment]
Leo, many thanks for all the time you put into this! I owe you one ;) (and I promise I"ll complete the OpenBis answer :)

**Comment by ltalirz** [comment]
done with the read through!
the remaining changes are really quite minor. 
looks very good to me!


I'll still have to actually properly do the exercise once again and sumit my result - unfortunately one cannot really do this at the same time or one messes up the code cells...

**Comment by kjappelbaum** [comment]
Thanks a lot for all the time you put into this! It really improved it a lot!

**Comment by ltalirz** [comment]
you're welcome :-)

**Pull request merged**
